name: deploy-to-serverless

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout repo
        uses: actions/checkout@master
        with:
          repository: kimpinot/plog

      - name: node.js 설정
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: yarn 설치
        run: npm install -g yarn

      - name: dependency 설치
        run: yarn install

      - name: prisma clinet 생성
        run: yarn prisma:generate

      - name: serverless 배포
        run: yarn deploy
